project:
  genome: "data/drosophila/Drosophila_melanogaster.BDGP6.54.dna_sm.toplevel.fa"
  input: "data/drosophila/Nanopore_drosophila_mix.clean.fastq"
  outdir: "results/drosophila_SQevi_nanopore"
  toolsdir: "/home/patienza/Programs/lr_annotation"
  log_level: "INFO"

training:
  lineage: "drosophila_odb12"
  miniprot_threshold: 0.95
  flanking_region: 1000
  test_size: 5000

prediction:
  species: "drosophila_melanogaster_mine"
  mode: "split"
  utr: False

curation:
  mode: "placebo"
  filter_rules: "data/filter_rules.json"

evaluation:
  reference_gtf: "data/drosophila/Drosophila_melanogaster.BDGP6.54.115.gtf"
  omark_db: "LUCA"
  omark_taxid: 7227

resources:
  small:
    cpus: 2
    mem: "8G"
    time: "2h"
    qos: "short"
  medium:
    cpus: 8
    mem: "120G"
    time: "10h"
    qos: "short"
  big:
    cpus: 10
    mem: "30G"
    time: "24h"
    qos: "long"
  busco:
    cpus: 30
    mem: "60G"
    time: "240h"
    qos: "long"
  small_bigMem:
    mem: "30G"
