required:
  genome: ""
  input: ""
  outdir: "results"
  toolsdir: "/home/pabloati/Programs/lr_annotation"
  log_level: "INFO"  # Logging level: DEBUG, INFO, WARNING, ERROR
augustus:
  prediction: "ab_initio" # Options: "ab_initio" or "evidence_driven"
  reference_gtf: "data/mm39.ncbiRefSeq.gtf"
  species_name: "trial"
  utr: True
  mode: split
qc:
  omark_db: Metazoa
  omark_taxid: 10090
ab_initio:
  busco_downloads: "busco_downloads"
  lineage: "eutheria_odb10"
  miniprot_threshold: 0.95 # Minimum identity threshold for miniprot gene models
  flanking_region: 1000
  test_size: 5000
resources:
  big:
    cpus: 10
    mem_mb: 20480
    time_min: 1440
    qos: long
  busco:
    cpus: 30
    mem_mb: 61440
    time_min: 7200
    qos: long
  small:
    cpus: 2
    mem_mb: 8192
    time_min: 120
    qos: short
  small_bigMem:
    mem_mb: 20480
  medium:
    cpus: 8
    mem_mb: 12288
    time_min: 600
    qos: short
