required:
  genome: "data/sac_cerevisiae/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa"
  input: "data/sac_cerevisiae/SRR11589287_cluster_singletons.bam"
  outdir: "results/saccharomyces_cerevisiae_SQevi"
  toolsdir: "/home/patienza/Programs/lr_annotation"
  log_level: "INFO"
sqanti:
  json_rules: "data/filter_rules.json"
augustus:
  prediction: ab_initio
  reference_gtf: ""
  species_name: "sac_cerevi_SQevi"
  utr: False
  mode: split
qc:
  omark_db: LUCA
  omark_taxid: 4932
ab_initio:
  lineage: "saccharomycetaceae_odb12"
  miniprot_threshold: 0.95
  flanking_region: 1000
  test_size: 5000
resources:
  big:
    cpus: 10
    mem: 30G
    time: 24h
    qos: long
  busco:
    cpus: 30
    mem: 60G
    time: 240h
    qos: long
  small:
    cpus: 2
    mem: 8G
    time: 2h
    qos: short  
  small_bigMem:
    mem: 30G
  medium:
    cpus: 8
    mem: 120G
    time: 10h
    qos: short
